# Loads default set of integrations. Do not remove.
default_config:
homeassistant:
  packages:
    hue_scene_selector: !include hue_scene_selector.yaml
# Load frontend themes from the themes folder
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /www/community/hass-hue-icons/hass-hue-icons.js
    - /www/community/lovelace-card-mod/card-mod.js

panel_iframe:
  webtop:
    title: "Webtop"
    icon: mdi:desktop-tower-monitor
    url: "https://web.methodist1.duckdns.org"
   #or wherever you ended up putting card-mod.js


ffmpeg:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# TLS with letsencrypt add-on
#http:
# ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
http:

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.32.0/23
    - 172.30.0.0/23
    - 172.30.232.0/23
    - 192.168.0.0/16  # (optional, if accessing from LAN)

group: !include groups.yaml
sensor:
  - platform: time_date
    display_options:
      - time
      - date
      - time_date
      - date_time_utc